// DevConnect.Web/src/app/modules/home/home.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css']
})
export class HomeComponent {
  constructor(private router: Router) {}

  goToFeed() {
    this.router.navigate(['/feed']);
  }
}

<div class="home-container">
    <h1>Welcome to <span>DevConnect</span></h1>
    <p>Your place to share, connect, and grow as a developer.</p>
    <button (click)="goToFeed()">Explore Feed</button>
  </div>

// devconnect-web/src/pages/Home.vue
<template>
    <div class="container">
      <div class="card" style="text-align: center;">
        <h1>Welcome to <span style="color: #007bff;">DevConnect</span></h1>
        <p>A place for developers to share ideas, connect, and grow together.</p>
        <router-link to="/feed">
          <button>Go to Feed</button>
        </router-link>
      </div>
    </div>
  </template>
