// DevConnect.Web/src/app/modules/feed/feed-list/feed-list.component.ts
import { Component, OnInit } from '@angular/core';
import { PostsService, Post } from 'src/app/services/posts.service';

@Component({
  selector: 'app-feed-list',
  templateUrl: './feed-list.component.html',
  styleUrls: ['./feed-list.component.css']
})
export class FeedListComponent implements OnInit {
  posts: Post[] = [];

  constructor(private postsService: PostsService) {}

  ngOnInit(): void {
    this.postsService.getPosts().subscribe(data => this.posts = data);
  }
}

<div class="feed-container">
  <h2>Latest Posts</h2>
  <div class="post-card" *ngFor="let post of posts">
    <h3>{{ post.title }}</h3>
    <p>{{ post.content }}</p>
  </div>
</div>

// devconnect-web/src/components/Feed/FeedList.vue
<template>
    <div>
      <div v-for="post in posts" :key="post.id" class="card">
        <h3>{{ post.title }}</h3>
        <p>{{ post.content }}</p>
      </div>
    </div>
  </template>
  
  <script setup>
  import { ref, onMounted } from 'vue';
  import { getPosts } from '../../services/post.service';
  
  const posts = ref([]);
  
  onMounted(async () => {
    const res = await getPosts();
    posts.value = res.data;
  });
  </script>
